---
skip-check:
  # IAM Resourcing using wildcards
  - CKV_AWS_356
  - CKV_AWS_111

  # Lambda Encryption and Dead Letter Queue
  - CKV_AWS_173
  - CKV_AWS_116

  # Cloudwatch Logs KMS Encryption and Retention
  - CKV_AWS_158
  - CKV_AWS_338

  # Pin module sources to a commit hash (false positive)
  - CKV_TF_1

  # Ignore adding code-signing to Lambda.
  # It is not needed here since our Lambda functions use container
  # images over uploading .zip files for layers.
  - CKV_AWS_272

  # API Gateway methods are unrestricted
  # This is fine as there are other layers of security in place
  # We want some endpoints (i.e. the health checks) to be publicly accessible
  - CKV_AWS_59

  # API Gateway requests are not validated
  - CKV2_AWS_53

  # Client certificate authentication is not used
  - CKV2_AWS_51

  # WAF Logging using Amazon Kinesis Data Firehose
  - CKV2_AWS_31

  # API Gateway caching is not enabled
  - CKV_AWS_120
